/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatproject;

import com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkHardIJTheme;
import javax.swing.JOptionPane;


/**
 *
 * @author Nicopau
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ChatClient ircClient;

    

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        areaTxtChat.setEditable(false);
        areaTxtParticipants.setEditable(false);
        areaTxtInfo.setEditable(false);
        ircClient = new ChatClient(this);
        btnDisconnect.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTxtChat = new javax.swing.JTextArea();
        lblServerIp = new javax.swing.JLabel();
        txtServerIp = new javax.swing.JTextField();
        lblChannel = new javax.swing.JLabel();
        txtChannel = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        txtMsg = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTxtParticipants = new javax.swing.JTextArea();
        lblParticipants = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTxtInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaTxtChat.setColumns(20);
        areaTxtChat.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        areaTxtChat.setRows(5);
        jScrollPane1.setViewportView(areaTxtChat);

        lblServerIp.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        lblServerIp.setText("Server");

        txtServerIp.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txtServerIp.setText("irc.libera.chat");
        txtServerIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerIpActionPerformed(evt);
            }
        });

        lblChannel.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        lblChannel.setText("Channel");

        txtChannel.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txtChannel.setText("#");

        lblUsername.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnConnect.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnDisconnect.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        txtMsg.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        btnSend.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        areaTxtParticipants.setColumns(20);
        areaTxtParticipants.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        areaTxtParticipants.setRows(5);
        jScrollPane2.setViewportView(areaTxtParticipants);

        lblParticipants.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        lblParticipants.setText("Participants");

        lblChat.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        lblChat.setText("Chat");

        areaTxtInfo.setColumns(20);
        areaTxtInfo.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        areaTxtInfo.setRows(5);
        jScrollPane3.setViewportView(areaTxtInfo);

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel1.setText("Informational");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDisconnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblServerIp)
                                    .addComponent(lblChannel)
                                    .addComponent(lblUsername))
                                .addGap(0, 199, Short.MAX_VALUE))
                            .addComponent(txtChannel)
                            .addComponent(txtServerIp)
                            .addComponent(jScrollPane2))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblParticipants)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblChat)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnSend))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblServerIp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChannel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConnect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisconnect)
                        .addGap(33, 33, 33)
                        .addComponent(lblParticipants)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSend)
                            .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        ircClient.sendMessage();
        txtMsg.setText("");
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        if (ircClient.getIrcSocket().isConnected()){
            ircClient.disconnect();
            btnDisconnect.setEnabled(false);
            btnConnect.setEnabled(true);
        }
            btnDisconnect.setEnabled(false);
            btnConnect.setEnabled(true);
        
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if (txtServerIp.getText().equals("") || txtChannel.getText().equals("") || txtUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "All fields must be filled.", "Error", JOptionPane.PLAIN_MESSAGE);

        } else{
            String server = txtServerIp.getText();
            String channel = txtChannel.getText();
            String username = txtUsername.getText();

            ircClient.serverConnect(username, channel, server);
        }

        btnDisconnect.setEnabled(true);
        btnConnect.setEnabled(false);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtServerIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServerIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerIpActionPerformed
    
    public void addMessageToChat(String message) {
        areaTxtChat.append("SERVER | " + message + "\n");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            FlatGruvboxDarkHardIJTheme.setup();
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTxtChat;
    private javax.swing.JTextArea areaTxtInfo;
    private javax.swing.JTextArea areaTxtParticipants;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblChannel;
    private javax.swing.JLabel lblChat;
    private javax.swing.JLabel lblParticipants;
    private javax.swing.JLabel lblServerIp;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtChannel;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JTextField txtServerIp;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    String getMessage() {
        return txtMsg.getText();
    }

    void writeInfo(String info) {
        areaTxtInfo.append(info);
    }
}
